dist: bionic
language: generic

services:
  - docker

env:
  matrix:
    - TARGET=lint
    - TARGET=ts
    - TARGET=test CONSTEL=export
    - TARGET=test CONSTEL=misc
    - TARGET=test CONSTEL=misc JQUERY=true
    - TARGET=test CONSTEL=ui
    - TARGET=test CONSTEL=ui.editors
    - TARGET=test CONSTEL=ui.grid
    - TARGET=test CONSTEL=ui.scheduler
    - TARGET=test CONSTEL=viz
    - TARGET=test MOBILE_UA=ios9 JQUERY=true CONSTEL=ui
    - TARGET=test MOBILE_UA=ios9 JQUERY=true CONSTEL=ui.editors
    - TARGET=test MOBILE_UA=ios9 JQUERY=true CONSTEL=ui.grid
    - TARGET=test MOBILE_UA=ios9 JQUERY=true CONSTEL=ui.scheduler
    - TARGET=test MOBILE_UA=ios9 JQUERY=true CONSTEL=viz
    - TARGET=test BROWSER=firefox CONSTEL=export
    - TARGET=test BROWSER=firefox CONSTEL=misc
    - TARGET=test BROWSER=firefox CONSTEL=ui
    - TARGET=test BROWSER=firefox CONSTEL=ui.editors
    - TARGET=test BROWSER=firefox CONSTEL=ui.grid
    - TARGET=test BROWSER=firefox CONSTEL=ui.scheduler
    - TARGET=test BROWSER=firefox CONSTEL=viz
    - TARGET=test_functional COMPONENT=dataGrid
    - TARGET=test_functional COMPONENT=scheduler
    - TARGET=test_functional COMPONENT=editors
    - TARGET=test_functional COMPONENT=navigation
    - TARGET=test_themebuilder

cache:
  directories:
    - node_modules
    - dotnet_packages

before_cache:
  # See https://github.com/DevExpress/DevExtreme/pull/1251
  - sudo chmod -R +Xr dotnet_packages

script:

  # clean bloated PATH to prevent conflicts
  - export PATH=/usr/sbin:/usr/bin:/sbin:/bin

  - >
    docker run -t
    -e HEADLESS=true
    -e TARGET=$TARGET
    -e BROWSER=$BROWSER
    -e CONSTEL=$CONSTEL
    -e COMPONENT=$COMPONENT
    -e JQUERY=$JQUERY
    -v $TRAVIS_BUILD_DIR:/devextreme
    docker.io/devexpress/devextreme-build:19_2
    ./docker-ci.sh
