name: DevExtreme Angular Tests

on:
  pull_request:
  push:
    branches: [23_2]

env:
  NX_SKIP_NX_CACHE: ${{ (github.event_name != 'pull_request' || contains( github.event.pull_request.labels.*.name, 'skip-cache')) && 'true' || 'false' }}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Get sources
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.18.2'

    - name: Get npm cache directory
      id: npm-cache-dir
      shell: bash
      run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

    - name: Restore npm cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ github.workflow }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install npm packages
      run: npm i --no-audit --no-fund

      # m.b. move to lint.yml?
    - name: Run lint
      working-directory: ./packages/devextreme-angular
      run: npm run lint

    - name: Build devextreme package
      working-directory: ./packages/devextreme
      run: npm run build

    - name: Generate wrappers
      run: npm run angular:regenerate

    - name: Check generated code
      shell: bash
      run: |
        git add . -N
        changes=$(git diff --name-status HEAD -- packages/devextreme-angular/src)
        if [ -n "$changes" ]; then
          echo "Generated code is outdated. The following files have uncommitted changes:"
          echo "$changes";
          echo "To update generated code, use "npm run regenerate-all" and commit changes."
          exit 1
        fi

    - name: Build wrappers
      working-directory: ./packages/devextreme-angular
      run: npm run build

    - name: Run tests
      working-directory: ./packages/devextreme-angular
      run: npm run test:dev

    - name: Check packing
      working-directory: ./packages/devextreme-angular
      run: npm run pack

    - name: Archive internal-tools artifacts
      uses: actions/upload-artifact@v3
      with:
        name: internal-tools-artifacts
        path: artifacts/internal-tools/
        retention-days: 7
