name: DevExtreme Vue Tests

on:
  pull_request:
  push:
    branches: [23_2]

env:
  NX_SKIP_NX_CACHE: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Get sources
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.18.2'

    - name: Restore npm cache
      uses: actions/cache@v3
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-modules

    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '3.1.x'

    - name: Install npm packages
      run: npm i --no-audit --no-fund

    # m.b. move to lint.yml?
    - name: Run lint
      working-directory: ./packages/devextreme-vue
      run: npm run lint

    - name: Build devextreme package
      run: |
        npx nx build devextreme-main

    - name: Generate wrappers
      run: npm run vue:regenerate

    - name: Check generated code
      shell: bash
      run: |
        git add . -N
        changes=$(git diff --name-status HEAD -- packages/devextreme-vue/src)
        if [ -n "$changes" ]; then
          echo "Generated code is outdated. The following files have uncommitted changes:"
          echo "$changes";
          echo "To update generated code, use "npm run regenerate-all" and commit changes."
          exit 1
        fi

    - name: Archive internal-tools artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: internal-tools-artifacts
        path: ./artifacts/internal-tools/
        retention-days: 7

    - name: Run tests with Vue
      working-directory: packages/devextreme-vue
      run: npm run test

    - name: Check packing
      run: npx nx run-many -t pack -p devextreme-vue

