name: Renovation

on: [push, pull_request]

jobs:
  compile-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Get sources
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15'

    - name: Restore npm cache
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: ${{ runner.os }}-node-modules-v2-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-v2

    - name: Run npm install
      run: npm install --no-package-lock --no-audit --no-fund

    - name: Compile renovation
      run: npm run compile:r

    - name: Lint renovation
      run: npx eslint --ext .tsx,.ts,.d.ts  ./js/renovation

  jest-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Get sources
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15'

    - name: Restore npm cache
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules

    - name: Run npm install
      run: npm install --no-package-lock --no-audit --no-fund
    - name: Jest test
      run: |
        npm i
        npx gulp localization
        npm run test-jest
