name: Run TestCafe on gh-pages branch

on:
  workflow_dispatch:

jobs: 
    testcafe: 
        strategy:
            fail-fast: false
            matrix:
              CONSTEL: [react(1/4), react(2/4), react(3/4), react(4/4), vue(1/4), vue(2/4), vue(3/4), vue(4/4), angular(1/4), angular(2/4), angular(3/4), angular(4/4)]
              THEME: ['generic.light', 'material.blue.light', 'fluent.blue.light']


        runs-on: ubuntu-latest
        name: testcafe-${{ matrix.CONSTEL }}-${{ matrix.THEME }}
        timeout-minutes: 60
        env:
          TARGET_BRANCH: ${{ github.ref_name }}

        steps:
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20'
            
            - name: Checkout gh-pages branch
              uses: actions/checkout@v4
              with:
                ref: gh-pages
                path: gh-pages

            - name: Run Web Server
              working-directory: gh-pages
              run: |
                python -m http.server 8080 &
                python -m http.server 8081 &
                python -m http.server 8082 &
                python -m http.server 8083 &

            - name: Checkout main branch
              uses: actions/checkout@v2
              with:
                ref: ${{ env.TARGET_BRANCH }}
                path: devextreme
            
            - name: Console.log ls
              run: ls -al & cd gh-pages & ls -al

            - name: Setup Chrome
              uses: ./devextreme/.github/actions/setup-chrome
              with:
                chrome-version: '121.0.6167.160'

            - name: DevExtreme - Install packages
              working-directory: devextreme
              run: npm install --no-audit --no-fund
            
            - name: Run TestCafe tests
              working-directory: devextreme/apps/demos
              env:
                CHANGEDFILEINFOSPATH: changed-files.json
                BROWSERS: chrome --headless=new --disable-partial-raster --disable-skia-runtime-opts --run-all-compositor-stages-before-draw --disable-new-content-rendering-timeout --disable-threaded-animation --disable-threaded-scrolling --disable-checker-imaging --disable-image-animation-resync --use-gl="swiftshader" --disable-features=PaintHolding --js-flags=--random-seed=2147483647 --font-render-hinting=none --disable-font-subpixel-positioning
                #DEBUG: hammerhead:*,testcafe:*
                CONCURRENCY: 4
                TCQUARANTINE: true
                CONSTEL: ${{ matrix.CONSTEL }}
                THEME: ${{ matrix.THEME }}
                ISGITHUBDEMOS: true
                # DISABLE_DEMO_TEST_SETTINGS: all # Uncomment to ignore all the visualtestrc.json settings
                # DISABLE_DEMO_TEST_SETTINGS: ignore # Uncomment to ignore the `ignore` field
                # DISABLE_DEMO_TEST_SETTINGS: comparison-options # Uncomment to ignore the `comparison-options` field
                CI_ENV: true # The `ignore` field in the visualtestrc.json should be disabled when running test locally
              run: npx nx test-testcafe

            - name: Copy screenshots artifacts
              if: ${{ failure() }}
              uses: actions/upload-artifact@v3
              with:
                name: screenshots
                path: ${{ github.workspace }}/devextreme/apps/demos/testing/artifacts/compared-screenshots/**/*
                if-no-files-found: ignore
