name: TestCafe tests

concurrency:
  group: wf-${{github.event.pull_request.number || github.sha}}-${{github.workflow}}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches: [23_1]

jobs:
  build:
    name: build
    strategy:
      fail-fast: false

    runs-on: devextreme-shr2
    timeout-minutes: 15

    steps:
    - name: Get sources
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.18.2'

    - name: Restore npm cache
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-modules

    - name: Run npm install
      run: npm install --no-audit --no-fund

    - name: Build
      run: npm run build:testcafe

    - name: Zip artifacts
      run: |
        7z a -tzip -mx3 -mmt2 artifacts.zip artifacts scss/bundles

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: devextreme-artifacts
        path: artifacts.zip
        retention-days: 1

  testcafe:
    name: ${{ matrix.ARGS.name }}
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        ARGS: [
          { componentFolder: "common", name: "common" },
          { componentFolder: "common", name: "common - material", theme: 'material.blue.light' },
          { componentFolder: "treeList", name: "treeList", concurrency: 1 },
          { componentFolder: "dataGrid", name: "dataGrid (1/2)", indices: "1/2" },
          { componentFolder: "dataGrid", name: "dataGrid (2/2)", indices: "2/2" },
          { componentFolder: "pivotGrid", name: "pivotGrid", concurrency: 1 },
          { componentFolder: "pivotGrid", name: "pivotGrid - material", theme: 'material.blue.light', concurrency: 1 },
          { componentFolder: "scheduler", name: "scheduler (1/5)", indices: "1/5" },
          { componentFolder: "scheduler", name: "scheduler (2/5)", indices: "2/5" },
          { componentFolder: "scheduler", name: "scheduler (3/5)", indices: "3/5" },
          { componentFolder: "scheduler", name: "scheduler (4/5)", indices: "4/5" },
          { componentFolder: "scheduler", name: "scheduler (5/5)", indices: "5/5" },
          { componentFolder: "form", name: "form (1/2)", indices: "1/2" },
          { componentFolder: "form", name: "form (2/2)", indices: "2/2" },
          { componentFolder: "editors", name: "editors" },
          { componentFolder: "navigation", name: "navigation" },
          { componentFolder: "htmlEditor", name: "htmlEditor", concurrency: 1 },
          { componentFolder: "form", name: "form - material (1/2)", theme: 'material.blue.light', indices: "1/2" },
          { componentFolder: "form", name: "form - material (2/2)", theme: 'material.blue.light', indices: "2/2" },
          { componentFolder: "editors", name: "editors - material", theme: 'material.blue.light' },
          { componentFolder: "navigation", name: "navigation - material", theme: 'material.blue.light' },
          { componentFolder: "htmlEditor", name: "htmlEditor - material", theme: 'material.blue.light', concurrency: 1 },
        ]
    runs-on: devextreme-shr2
    timeout-minutes: 90

    steps:
    - name: Get sources
      uses: actions/checkout@v4

    - name: Setup Chrome
      uses: ./.github/actions/setup-chrome
      with:
        chrome-version: '116.0.5845.110'

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.18.2'

    - name: Restore npm cache
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-modules

    - name: Run npm install
      run: npm install --no-audit --no-fund

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: devextreme-artifacts

    - name: Prepare localization
      if: matrix.ARGS.componentFolder == 'renovation'
      run: npx gulp localization

    - name: Unpack artifacts
      run: 7z x artifacts.zip -aoa

    - name: Prepare renovation playground
      if: matrix.ARGS.componentFolder == 'renovation'
      run: |
        pushd testing/renovation
        npm install --no-audit --no-fund --legacy-peer-deps
        popd
        npm run build:react
        npx gulp build-renovation-testing

    - name: Run TestCafe tests
      run: |
        [ "${{ matrix.ARGS.theme }}" == "material.blue.light" ] && THEME="--theme ${{ matrix.ARGS.theme }}"
        [ "${{ matrix.ARGS.indices }}" != "" ] && INDICES="--indices ${{ matrix.ARGS.indices }}"
        [ "${{ matrix.ARGS.concurrency }}" != "" ] && CONCURRENCY="--concurrency ${{ matrix.ARGS.concurrency }}"
        [ "${{ matrix.ARGS.platform }}" != "" ] && PLATFORM="--platform ${{ matrix.ARGS.platform }}"
        all_args="--browsers=chrome:devextreme-shr2 --componentFolder ${{ matrix.ARGS.componentFolder }} $CONCURRENCY $INDICES $PLATFORM $THEME"
        echo "$all_args"
        npm run test-testcafe -- $all_args

    - name: Copy compared screenshot artifacts
      if: ${{ failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: compared-screenshots
        path: ${{ github.workspace }}/testing/testcafe/artifacts/compared-screenshots/**/*
        if-no-files-found: ignore
    - name: Copy failed test artifacts
      if: ${{ failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: failed-tests
        path: ${{ github.workspace }}/testing/testcafe/artifacts/failedtests/**/*
        if-no-files-found: ignore

  notify:
    runs-on: devextreme-shr2
    name: Send notifications
    needs: [build, testcafe]
    if: always() && contains(needs.*.result, 'failure')

    steps:
      - uses: actions/checkout@v4
      - uses: DevExpress/github-actions/send-teams-notification@main
        with:
          hook_url: ${{secrets.TEAMS_ALERT}}
          bearer_token: ${{secrets.GITHUB_TOKEN}}
          specific_repo: DevExpress/DevExtreme
          specific_branch: 23_1
